---

- hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: Creates a custom configured item
    my_module:
        name: "{{ item_name }}"
        description: "{{ item_description }}"
        sizeMB: "{{ item_sizeMB }}"
        path: "{{ item_path }}"
        state: present
