version: '2'
services:
  db:
    image: mysql:5.7.31
    environment:
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=rundeck
      - MYSQL_ROOT_PASSWORD=rundeck
    command: --character-set-server=utf8 --collation-server=utf8_bin
    volumes:
      - ./mysql:/var/lib/mysql
  rundeck:
      hostname: rundeck
      image: atilaloise/rundeck
      depends_on:
        - "db"
      environment:
        - EXTERNAL_SERVER_URL=http://localhost:4440
        - RUNDECK_ADMIN_PASSWORD=admin
        - DATABASE_URL=jdbc:mysql://db/rundeck?autoReconnect=true
        - RUNDECK_USER=rundeck
        - RUNDECK_PASSWORD=rundeck
        - DATABASE_ADMIN_USER=root
        - DATABASE_ADMIN_PASSWORD=rundeck
        - RUNDECK_PROJECT_STORAGE_TYPE=db
        - RUNDECK_STORAGE_PROVIDER=db
      volumes:
        - ./rundeck/var/lib/rundeck/var/storage:/var/lib/rundeck/var/storage
        - ./rundeck/opt/rundeck-plugins:/opt/rundeck-plugins
        - ./rundeck/var/rundeck:/var/rundeck
        - ./rundeck/var/lib/rundeck/.ssh:/var/lib/rundeck/.ssh
        - ./rundeck/etc/rundeck:/etc/rundeck
        - ./ssh_keys:/tmp/rundeck/ssh
        - ./acls:/tmp/rundeck/ACLS
      ports:
        - "4440:4440"
  jirasd:
    image: cptactionhank/atlassian-jira-service-desk:latest
    ports:
      - "8080:8080"
    volumes:
      - ./jira:/var/atlassian/jira
      - ./jiralogs/:/opt/atlassian/jira/logs
