version: '2'
services:
  db:
    image: mysql:5.7.31
    environment:
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=rundeck
      - MYSQL_ROOT_PASSWORD=rundeck
    command: --character-set-server=utf8 --collation-server=utf8_bin
    volumes:
      - ./mysql:/var/lib/mysql
  rundeck:
      hostname: rundeck
      image: atilaloise/rundeck
      depends_on:
        - "db"
      environment:
        - RUNDECK_ADMIN_PASSWORD=superp4ss
        - DATABASE_URL=jdbc:mysql://db/rundeck?autoReconnect=true
        - RUNDECK_USER=rundeck
        - RUNDECK_PASSWORD=rundeck
        - DATABASE_ADMIN_USER=root
        - DATABASE_ADMIN_PASSWORD=rundeck
      ports:
        - "4440:4440"